definitions:
  warehouse.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  warehouse.RequestBody:
    properties:
      name:
        type: string
    type: object
  warehouse.Warehouse:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact: {}
paths:
  /warehouses/:
    get:
      consumes:
      - application/json
      description: Get all warehouses
      operationId: list-warehouse
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/warehouse.Warehouse'
            type: array
      summary: Get all warehouses
      tags:
      - warehouses
    post:
      consumes:
      - application/json
      description: Create a warehouse with given data
      operationId: create-warehouse
      parameters:
      - description: Warehouse
        in: body
        name: warehouse
        required: true
        schema:
          $ref: '#/definitions/warehouse.RequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/warehouse.Warehouse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/warehouse.ErrorResponse'
      summary: Create a warehouse with given data
      tags:
      - warehouses
  /warehouses/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a warehouse by id
      operationId: delete-warehouse
      parameters:
      - description: Warehouse ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: NoContent
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/warehouse.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/warehouse.ErrorResponse'
      summary: Delete a warehouse by id
      tags:
      - warehouses
    get:
      consumes:
      - application/json
      description: Get single warehouse by id
      operationId: get-warehouse
      parameters:
      - description: Warehouse ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/warehouse.Warehouse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/warehouse.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/warehouse.ErrorResponse'
      summary: Get single warehouse by id
      tags:
      - warehouses
    put:
      consumes:
      - application/json
      description: Update a warehouse with given data
      operationId: update-warehouse
      parameters:
      - description: Warehouse ID
        in: path
        name: id
        required: true
        type: integer
      - description: Warehouse
        in: body
        name: warehouse
        required: true
        schema:
          $ref: '#/definitions/warehouse.RequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/warehouse.Warehouse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/warehouse.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/warehouse.ErrorResponse'
      summary: Update a warehouse with given data
      tags:
      - warehouses
swagger: "2.0"
