// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	dbclient "github.com/unicod3/horreum/pkg/dbclient"
)

// DataStorage is an autogenerated mock type for the DataStorage type
type DataStorage struct {
	mock.Mock
}

// NewDataCollection provides a mock function with given fields: tableName
func (_m *DataStorage) NewDataCollection(tableName string) dbclient.DataTable {
	ret := _m.Called(tableName)

	var r0 dbclient.DataTable
	if rf, ok := ret.Get(0).(func(string) dbclient.DataTable); ok {
		r0 = rf(tableName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dbclient.DataTable)
		}
	}

	return r0
}
