@startuml SystemContext
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include <office/Servers/database_server>

Person_Ext(Client, "Client", "A client with warehouses and goods in it")

ContainerDb_Ext(RDMS, "Relational Database", "Postgress")
AddElementTag("internal", $shape=EightSidedShape(), $bgColor="CornflowerBlue", $fontColor="white")

System_Boundary(Horreum, "Horreum"){
    Container(APIPackage, "API Package", "GIN", "OPEN API compatible REST API Implementation")
    Boundary(Internal, "Internal layer that contains business logic"){
        Container(Warehouse, "Warehouse Package", "INTERNAL", "Contains warehouse related business logic", $tags="internal")
        Container(Product, "Product Package", "INTERNAL", "Contains product and inventory related business logic", $tags="internal")
        Container(Article, "Article Package", "INTERNAL", "Contains article related business logic", $tags="internal")
        Container(Order, "Order Package", "INTERNAL", "Contains order related business logic", $tags="internal")
    }
    Rel(APIPackage, Warehouse, "Uses")
    Rel(APIPackage, Product, "Uses")
    Rel(APIPackage, Article, "Uses")
    Rel(APIPackage, Order, "Uses")

    Boundary(Pkg, "Pkg layer"){
        Container(DBPackage, "Database Package", "UPPER/DB", "Abstracts away database implementation details")
        Container(Streamer, "Streamer Package", "WATERMILL", "Abstracts away the WATERMILL library and provides an api to stream events to topics internally   aka:pub/sub")
        Rel_L(Streamer, DBPackage, "Uses")

    }
    Rel(Warehouse, DBPackage, "Uses")
    Rel(Product, DBPackage, "Uses")
    Rel(Article, DBPackage, "Uses")
    Rel(Order, DBPackage, "Uses")
    Rel(Order, Streamer, "PushMessage")


    Rel(DBPackage, RDMS, "Uses")
}

Rel(Client, APIPackage, "Uses", "REST API")

SHOW_LEGEND()
@enduml