// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	message "github.com/ThreeDotsLabs/watermill/message"
	mock "github.com/stretchr/testify/mock"

	streamer "github.com/unicod3/horreum/pkg/streamer"
)

// Streamer is an autogenerated mock type for the Streamer type
type Streamer struct {
	mock.Mock
}

// NewChannel provides a mock function with given fields:
func (_m *Streamer) NewChannel() *streamer.Channel {
	ret := _m.Called()

	var r0 *streamer.Channel
	if rf, ok := ret.Get(0).(func() *streamer.Channel); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*streamer.Channel)
		}
	}

	return r0
}

// RegisterHandler provides a mock function with given fields: channel, topicName, handlerFunc
func (_m *Streamer) RegisterHandler(channel streamer.Channel, topicName string, handlerFunc message.NoPublishHandlerFunc) {
	_m.Called(channel, topicName, handlerFunc)
}
